apiVersion: v1
kind: Service
metadata:
  name: wireguard-client-svc
  labels:
    app: wireguard-client
spec:
  type: ClusterIP
  selector:
    app: wireguard-client
  ports:
    - name: envoy
      port: 15432
      targetPort: 15432
      protocol: TCP
